/**
 * data/brick-icons.js is GENERATED from the brick engine's own icon functions (editor/editor-brick-tool.js) at the sizes
 * the panel asks for (BRICK_ICON_SIZES; ids from their own declared lists). This test lays every icon fresh and fails
 * when the shipped data differs -- an engine change that alters an icon must regenerate it:
 *     node tools/gen_brick_icons.mjs           # (re)write data/brick-icons.js
 *     node tools/gen_brick_icons.mjs --check   # exit 1 if it is stale
 * 2026-10-08 (MEASURED): laying these icons at boot was 2.4 of a 7 s phone first load (4x CPU, 390 px).
 */
import { describe, it, expect } from 'vitest';
import { writeFileSync } from 'node:fs';
import BRICK_ICONS from '../bspline-frame-builder/b-spline-gen/html/data/brick-icons.js';
import {
  BRICK_ICON_SIZES, FRAME_CORNERS, wallPatternIconSvg, framePresetIconSvg, frameCornerIconSvg, fanCentreIconSvg, accentIconSvg,
  clearBrickIconCaches, setBrickIconDeclared, sizedIconSvg, PATTERN_ICON_BOARD, ACCENT_ICON_BOARD,
} from '../bspline-frame-builder/b-spline-gen/html/editor/editor-brick-tool.js';
import { BRICK_PATTERNS, FRAME_PRESETS } from '../bspline-frame-builder/b-spline-gen/html/core/bricks/library.js';
import { FAN_CENTRES } from '../bspline-frame-builder/b-spline-gen/html/core/bricks/fan-centre.js';
import { ACCENT_PRESETS } from '../bspline-frame-builder/b-spline-gen/html/editor/brick-accents.js';

const OUT = 'bspline-frame-builder/b-spline-gen/html/data/brick-icons.js';
const HEADER = '// GENERATED by tools/gen_brick_icons.mjs (tests/brick-icons-fresh.test.js) from the brick engine. Do not edit.\nexport default ';
const S = BRICK_ICON_SIZES;
const wPattern = (px) => Math.round((px * PATTERN_ICON_BOARD.widthIn) / PATTERN_ICON_BOARD.heightIn);
const wAccent = (px) => Math.round((px * ACCENT_ICON_BOARD.widthIn) / ACCENT_ICON_BOARD.heightIn);
/** Every declared icon: [kind, base key, sizes, (px) -> width, (px) -> the icon laid fresh at that size]. */
const ICONS = [
  ...Object.keys(BRICK_PATTERNS).map((id) => ['pattern', id, S.pattern, wPattern, (px) => wallPatternIconSvg(id, px)]),
  ...Object.entries(FRAME_PRESETS).filter(([, b]) => b.length).map(([id]) => ['preset', id, S.preset, (px) => px, (px) => framePresetIconSvg(id, px)]),
  ...FRAME_CORNERS.map(({ id }) => ['corner', id, S.corner, (px) => px, (px) => frameCornerIconSvg(id, px)]),
  ...FAN_CENTRES.map(({ id }) => ['fan', id, S.fan, (px) => px, (px) => fanCentreIconSvg(id, px)]),
  ...['none', ...ACCENT_PRESETS.map((a) => a.id)].flatMap((id) => [false, true].map((sunk) =>
    ['accent', `${id}:${sunk ? 's' : 'r'}:stretcher`, S.accent, wAccent, (px) => accentIconSvg(id, px, { sunk })])),
];

/** Every icon laid fresh by the engine (the declared data ignored): the data to ship, and every size's own lay. */
export function layAllIcons() {
  setBrickIconDeclared(false);
  clearBrickIconCaches();
  try {
    const data = { pattern: {}, preset: {}, corner: {}, fan: {}, accent: {} }, sized = [];
    for (const [kind, base, sizes, width, lay] of ICONS) {
      data[kind][base] = lay(sizes[0]); // ONE drawing per icon, at its first size
      for (const px of sizes) sized.push([kind, base, px, width(px), lay(px)]);
    }
    return { data, sized };
  } finally {
    clearBrickIconCaches();
    setBrickIconDeclared(true);
  }
}

describe('data/brick-icons.js is fresh (the engine\'s own icons, declared)', () => {
  it('equals every icon laid now by the engine, at every declared size', () => {
    const { data, sized } = layAllIcons();
    if (process.env.BRICK_ICONS_WRITE === '1') {
      writeFileSync(OUT, HEADER + JSON.stringify(data) + ';\n');
      return;
    }
    for (const kind of Object.keys(data)) expect(Object.keys(BRICK_ICONS[kind] || {}).sort(), `${kind}: the declared icons`).toEqual(Object.keys(data[kind]).sort());
    for (const kind of Object.keys(data)) for (const base of Object.keys(data[kind])) {
      if (BRICK_ICONS[kind][base] !== data[kind][base]) throw new Error(`stale icon ${kind} ${base} -- run: node tools/gen_brick_icons.mjs`);
    }
    // the size rule the app relies on (sizedIconSvg): every size's own lay === the declared drawing at that size
    for (const [kind, base, px, w, laid] of sized) {
      if (sizedIconSvg(BRICK_ICONS[kind][base], w, px) !== laid) throw new Error(`${kind} ${base} at ${px} px is not the declared drawing resized`);
    }
  }, 600000);
});
