/**
 * editor-fonts.js — Single source of truth for the editor's bundled fonts.
 *
 * The .ttf files under b-spline-gen/html/fonts/ are used in two places:
 *   1) opentype.js loads them in editor-expand.js to convert text into
 *      SVG paths during stamp/export.
 *   2) The on-screen Symbol Keyboard (.symbol-key buttons) renders glyphs
 *      in those families. Windows ships Symbol/Wingdings/Webdings/Segoe UI
 *      Symbol as system fonts, but iOS, Android and Linux do NOT — without
 *      explicit @font-face the keyboard falls back to the system font and
 *      shows plain Latin glyphs in place of α, β, ☼, etc.
 *
 * Keeping both paths in sync used to be manual (one map in JS, separate
 * @font-face block in editor.css) and that drifted apart at least three
 * times, breaking the Symbol Keyboard on iOS each time. To prevent that:
 *
 *   - FONT_MAP below is the single source of truth (family → ttf file).
 *   - injectFontFaceRules() runs once at editor init and registers every
 *     symbol family in the document via a generated <style> tag, with
 *     URLs resolved relative to THIS module so it survives page moves.
 *   - verifyFontLoaded(family) lets callers self-check the result; the
 *     Symbol Keyboard uses it to show a visible banner the next time a
 *     font fails to load, instead of silently rendering wrong glyphs.
 *
 * Adding a new symbol font is a one-line change here. The opentype path,
 * the on-screen keyboard, and the runtime self-test all pick it up.
 */

export const FONT_MAP = {
    "Arial": "arial.ttf",
    "Tahoma": "tahoma.ttf",
    "Verdana": "verdana.ttf",
    "Bahnschrift": "bahnschrift.ttf",
    "Impact": "impact.ttf",
    "Georgia": "georgia.ttf",
    "Times New Roman": "times.ttf",
    "Courier New": "courier.ttf",
    "Cascadia Code": "CascadiaCode-Regular.ttf",
    "Cascadia Mono": "CascadiaMono-Regular.ttf",
    "Marlett": "marlett.ttf",
    "Symbol": "symbol.ttf",
    "Webdings": "webdings.ttf",
    "Wingdings": "wingdings.ttf",
    "Segoe UI Symbol": "segoe-symbols.ttf",
    "Segoe MDL2 Assets": "segoe-mdl2.ttf",
    "Segoe Fluent Icons": "segoe-fluent-icons.ttf",
    "Segoe UI Emoji": "segoe-emoji.ttf"
};

/**
 * Symbol families that DON'T ship on iOS/Android/Linux. These are the
 * ones we must register as @font-face for the on-screen keyboard to
 * render correctly cross-platform. Common Latin fonts (Arial, Tahoma,
 * Verdana, etc.) are intentionally excluded — they exist on every OS,
 * so registering them would just waste bandwidth re-downloading a font
 * the device already has.
 *
 * The on-screen-keyboard self-test (verifyFontLoaded) runs against this
 * set; anything in here that fails to load triggers the warning banner.
 */
export const SYMBOL_FAMILIES = new Set([
    "Symbol",
    "Wingdings",
    "Webdings",
    "Segoe UI Symbol",
    "Segoe MDL2 Assets",
    "Segoe Fluent Icons",
    "Segoe UI Emoji"
]);

/**
 * Resolve a font filename to an absolute URL relative to THIS module.
 * Using import.meta.url means the path stays correct no matter which
 * page imports the module — no more relative-path drift bugs.
 */
function fontUrl(file) {
    return new URL(`../fonts/${file}`, import.meta.url).href;
}

let _injected = false;

/**
 * Inject @font-face rules for every entry in SYMBOL_FAMILIES into the
 * current document. Idempotent — safe to call from multiple init paths.
 *
 * Logs a console warning if any symbol family is listed in
 * SYMBOL_FAMILIES but missing from FONT_MAP, so the two never silently
 * drift apart again.
 */
export function injectFontFaceRules() {
    if (_injected) return;
    if (typeof document === 'undefined') return; // SSR / non-DOM contexts
    _injected = true;

    const rules = [];
    for (const family of SYMBOL_FAMILIES) {
        const file = FONT_MAP[family];
        if (!file) {
            console.warn(`[editor-fonts] SYMBOL_FAMILIES lists "${family}" but FONT_MAP has no entry — skipping. Update FONT_MAP in editor-fonts.js.`);
            continue;
        }
        rules.push(
            `@font-face {\n` +
            `    font-family: '${family}';\n` +
            `    src: url('${fontUrl(file)}') format('truetype');\n` +
            `    font-display: swap;\n` +
            `}`
        );
    }

    const style = document.createElement('style');
    style.id = 'editor-font-faces';
    style.dataset.source = 'editor-fonts.js';
    style.textContent =
        `/* Generated by editor-fonts.js. Do not edit by hand — change FONT_MAP / SYMBOL_FAMILIES instead. */\n` +
        rules.join('\n');
    document.head.appendChild(style);

    console.log(`[editor-fonts] Injected ${rules.length} @font-face rule(s) for symbol families.`);
}

/**
 * Returns true if `family` is actually loaded and usable, false if the
 * browser failed to fetch or parse the font.
 *
 * Uses the FontFace Loading API. document.fonts.load() forces a fetch
 * (font-display: swap means the browser otherwise lazy-loads) and
 * resolves once the font is loaded or known unavailable.
 *
 * On browsers without the FontFace API, returns true (assume OK) so we
 * don't show false-positive banners on legacy environments.
 */
export async function verifyFontLoaded(family) {
    if (typeof document === 'undefined' || !('fonts' in document)) return true;
    try {
        const faces = await document.fonts.load(`16px "${family}"`);
        if (!faces || faces.length === 0) return false;
        return document.fonts.check(`16px "${family}"`);
    } catch (err) {
        console.warn(`[editor-fonts] verifyFontLoaded("${family}") threw:`, err);
        return false;
    }
}
