"""
gen_frame_defs.py — FB-APP S1: generate the app's frame-defs.json from the
frame builder's own Python declarations (one source; never hand-edit the JSON).

    python tools/gen_frame_defs.py           # (re)write the file
    python tools/gen_frame_defs.py --check   # exit 1 if the file is stale

Source: fb_engine/frame_definition.py (common declarations) + every template
folder template_resolver discovers (its template_data.py + phase blocks).
Plain Python, with no Fusion / adsk import.
"""
import hashlib
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
FRAME_BUILDER = os.path.join(REPO, "bspline-frame-builder", "frame-builder")
OUT_PATH = os.path.join(REPO, "bspline-frame-builder", "b-spline-gen", "html", "data", "frame-defs.json")
# The same render as an ES module: the Fusion palette runs from file://, where
# fetch() of a JSON file is unreliable but module imports already work.
OUT_JS_PATH = OUT_PATH[:-len(".json")] + ".js"
JS_HEADER = "// GENERATED by tools/gen_frame_defs.py from the frame builder's Python. Do not edit.\nexport default "


def source_files():
    """Every file the definition is built from, in a stable order."""
    files = [os.path.join(FRAME_BUILDER, "fb_engine", "frame_definition.py"),
             os.path.join(FRAME_BUILDER, "fb_engine", "parameter_schema.py")]
    sketches = os.path.join(FRAME_BUILDER, "sketches")
    for root, dirs, names in os.walk(sketches):
        dirs[:] = sorted(d for d in dirs if d != "__pycache__")
        files += [os.path.join(root, n) for n in sorted(names) if n.endswith(".py")]
    return files


def source_hash():
    """sha256 over the sources with CRLF normalized, so a checkout's line
    endings never make the file look stale."""
    h = hashlib.sha256()
    for path in source_files():
        rel = os.path.relpath(path, FRAME_BUILDER).replace("\\", "/")
        with open(path, "rb") as f:
            h.update(rel.encode() + b"\0" + f.read().replace(b"\r\n", b"\n") + b"\0")
    return h.hexdigest()


def render():
    if FRAME_BUILDER not in sys.path:
        sys.path.insert(0, FRAME_BUILDER)
    from fb_engine.frame_definition import build_frame_defs
    defs = build_frame_defs(source_hash())
    return json.dumps(defs, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def render_js(text=None):
    return JS_HEADER + (text or render()).rstrip("\n") + ";\n"


def _read(path):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return f.read().replace("\r\n", "\n")


def main(argv):
    text = render()
    outputs = {OUT_PATH: text, OUT_JS_PATH: render_js(text)}
    if "--check" in argv:
        stale = [p for p, t in outputs.items() if _read(p) != t]
        if stale:
            print(f"STALE: {stale} -- run: python tools/gen_frame_defs.py")
            return 1
        print("frame-defs.json / frame-defs.js are fresh")
        return 0
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    for path, t in outputs.items():
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(t)
        print(f"wrote {path} ({len(t)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
